In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digit = load_digits()

In [2]:
Lr = LogisticRegression(solver='liblinear')
Sv = SVC()
Rf = RandomForestClassifier()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digit.data,digit.target,test_size=0.3)

In [4]:
Lr.fit(X_train,y_train)
Lr.score(X_test,y_test)

0.9648148148148148

In [5]:
Sv.fit(X_train,y_train)
Sv.score(X_test,y_test)

0.9833333333333333

In [6]:
Rf.fit(X_train,y_train)
Rf.score(X_test,y_test)

0.9777777777777777

**Basic Example**

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**For Our DataSet**

In [9]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=3)

score_Lr=[]
score_Sv=[]
score_Rf=[]

for train_index,test_index in kfold.split(digit.data,digit.target):
    X_train,X_test,y_train,y_test = digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    score_Lr.append(get_score(LogisticRegression(solver='liblinear'),X_train,X_test,y_train,y_test))
    score_Sv.append(get_score(SVC(gamma='scale'),X_train,X_test,y_train,y_test))
    score_Rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [11]:
score_Lr

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [12]:
score_Rf

[0.9232053422370617, 0.9482470784641068, 0.9198664440734557]

In [13]:
score_Sv

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

**get score by using package**

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(LogisticRegression(solver='liblinear'),digit.data,digit.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [16]:
cross_val_score(SVC(),digit.data,digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [17]:
cross_val_score(RandomForestClassifier(),digit.data,digit.target)

array([0.94166667, 0.90833333, 0.95821727, 0.97214485, 0.91364903])